### ISSUE TITLE
Running for hours but nothing seems to be deleted

### ISSUE THREAD

**Issue by laurie-kepford** [rancher/rancher-cleanup#3]
I have had this tool running for over an hour now:

There are thousands of log entries like this

```
++ kubectl get -o 'jsonpath={.metadata.finalizers}' token.management.cattle.io/kubeconfig-u-b86fdld8nj
+ FINALIZERS=
+ '[' x '!=' x ']'
+ kcd token.management.cattle.io/kubeconfig-u-b86fdld8nj
+ i=0
+ '[' 0 -lt 4 ']'
+ timeout 21 sh -c 'kubectl delete --ignore-not-found=true --grace-period=15 --timeout=20s token.management.cattle.io/kubeconfig-u-b86fdld8nj'
token.management.cattle.io "kubeconfig-u-b86fdld8nj" deleted
+ '[' 0 -eq 0 ']'
+ break
+ read NAME
+ kcpf token.management.cattle.io/kubeconfig-u-b86fdldgps
++ kubectl get -o 'jsonpath={.metadata.finalizers}' token.management.cattle.io/kubeconfig-u-b86fdldgps
+ FINALIZERS=
+ '[' x '!=' x ']'
+ kcd token.management.cattle.io/kubeconfig-u-b86fdldgps
+ i=0
+ '[' 0 -lt 4 ']'
+ timeout 21 sh -c 'kubectl delete --ignore-not-found=true --grace-period=15 --timeout=20s token.management.cattle.io/kubeconfig-u-b86fdldgps'
token.management.cattle.io "kubeconfig-u-b86fdldgps" deleted
+ '[' 0 -eq 0 ']'
+ break
+ read NAME
+ kcpf token.management.cattle.io/kubeconfig-u-b86fdldmx7
++ kubectl get -o 'jsonpath={.metadata.finalizers}' token.management.cattle.io/kubeconfig-u-b86fdldmx7
+ FINALIZERS=
+ '[' x '!=' x ']'
+ kcd token.management.cattle.io/kubeconfig-u-b86fdldmx7
+ i=0
+ '[' 0 -lt 4 ']'
+ timeout 21 sh -c 'kubectl delete --ignore-not-found=true --grace-period=15 --timeout=20s token.management.cattle.io/kubeconfig-u-b86fdldmx7'
token.management.cattle.io "kubeconfig-u-b86fdldmx7" deleted
+ '[' 0 -eq 0 ']'
+ break
+ read NAME
+ kcpf token.management.cattle.io/kubeconfig-u-b86fdldrz4
++ kubectl get -o 'jsonpath={.metadata.finalizers}' token.management.cattle.io/kubeconfig-u-b86fdldrz4
+ FINALIZERS=
```

And yet I still have the same number of deployment, pods, secrets, ets.

This cluster is about a year old, had two nodes and one downstream cluster.

Why would it take so long and appear to be making no progress?

**Comment by superseb** [comment]
Probably a side effect of https://github.com/rancher/rancher/issues/37705, I see a new token being deleted every time so the script seems to work fine but it seems the cluster contains a lot of tokens. We have some shortcuts in the cleanup script to delete all resources at once to save time, this seems to be a good new candidate for that.

Manual check of the resource count;

```
kubectl  get tokens.management.cattle.io --no-headers | wc -l
```

Probably needs to be added here; https://github.com/rancher/rancher-cleanup/blob/main/cleanup.sh#L253

**Comment by laurie-kepford** [comment]
Thanks for you quick response!!!
I stopped it.  Removed it. deleted the cattle-system namespace. Recreated the job. and it worked.

**Comment by superseb** [comment]
The fix for saving time by bulk deleting tokens is in https://github.com/rancher/rancher-cleanup/releases/tag/v1.0.1-rc1

**Comment by eliyamlevy** [comment]
Waiting for first v2.7.1 rc to merge pr.

**Comment by superseb** [comment]
This should be resolved in latest
