### ISSUE TITLE
cluster-api related resources deleted

### ISSUE THREAD

**Issue by lwabish** [rancher/rancher-cleanup#39]
My cluster has rancher installed, at the same time, I was trying cluster-api in this same cluster.
Just now I decided to uninstall rancher, after running this job, I found my cluster-api related resources are all deleted.

At first I thought this occurred because duplicate resource name like cluster etc. After checking the code, I understand that this script is intended to remove all cluster-api related resources.

So is it more reasonable to add an option to let user select whether to  keep cluster-api related resources?

If this feature looks ok, I'd love to implement it

**Comment by lwabish** [comment]
Sadly, found my istio was unintalled too...

**Comment by superseb** [comment]
This seems similar to #6, see https://github.com/rancher/rancher-cleanup/issues/6#issuecomment-1285476224 for a possible implementation. I'd be happy to review your PR.

**Comment by lwabish** [comment]
I tried adding another arg to the cleanup.sh, maybe not the best implement. #42
