### ISSUE TITLE
The cleanup script doesn't remove finalizers from namespaces

### ISSUE THREAD

**Issue by weeix** [rancher/rancher-cleanup#5]
Hi,

Thanks for being considerate and creating these scripts for those who need it. I used them to successfully cleanup Rancher and verify the cleanup result. However, some problem occurred after the cleanup: *namespaces can't be deleted as they would always stuck at "Terminating" state*. After some googling, I found the https://github.com/rancher/rancher/issues/14715 issue and finally able to delete them by editing the affected namespaces and delete the `controller.cattle.io/namespace-auth` finalizer.

It would be great if the cleanup script also delete the `controller.cattle.io/namespace-auth` finalizer from every namespaces.

Thank you.

**Comment by superseb** [comment]
@weeix The script removes both finalizers entries (see https://github.com/rancher/rancher-cleanup/blob/main/cleanup.sh#L72 where it calls `kcpf` function defined above it and removes finalizers itself too). Please supply logging output or a way to reproduce if this script didn't remove those as it should. 

Did you run it using a Job?

**Comment by superseb** [comment]
@weeix It could be the Job was pulling an older image, we just published `v1.0.0` which should also be `latest` so you can try that.

**Comment by weeix** [comment]
I already manually deleted the finalizers so I can't test it right now.
Sorry.

**Comment by macmiranda** [comment]
Biggest problem I'm facing now are the finalizers left on resources that do not belong to Rancher.

**Comment by 1kaushik1** [comment]
@macmiranda , im having the same problem, i can see finalizers set on clusterrolebindings of the aws-load-balancercontroller
```
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-08-03T13:21:57Z"
  finalizers:
  - wrangler.cattle.io/auth-prov-v2-crb
  labels:
```

**Comment by superseb** [comment]
As described in the README, ```This script will delete all Kubernetes resources belonging to/created by Rancher (including installed tools like logging/monitoring/opa gatekeeper/etc). ```. This won't interact with resources that are not described in the script as being from Rancher.

Not really sure how we should approach this, look for all resources that have deletionTimestamp, check for finalizers belonging to Rancher and delete the finalizers? If so, we can file a new issue and see what we can do (or someone can propose a PR but be aware that we want to keep this a safe way to cleanup a cluster so we should probably make this opt-in)

**Comment by gravufo** [comment]
> As described in the README, `This script will delete all Kubernetes resources belonging to/created by Rancher (including installed tools like logging/monitoring/opa gatekeeper/etc). `. This won't interact with resources that are not described in the script as being from Rancher.
> 
> Not really sure how we should approach this, look for all resources that have deletionTimestamp, check for finalizers belonging to Rancher and delete the finalizers? If so, we can file a new issue and see what we can do (or someone can propose a PR but be aware that we want to keep this a safe way to cleanup a cluster so we should probably make this opt-in)

Sorry for creeping, but I just hit this issue. The thing is, it affects resources that will also be deleted in the future. An actual fix would be to go through all objects that are ever updated/patched by Rancher and check if there are any finalizers in those that point to rancher and remove them.
