### ISSUE TITLE
'kubectl get nodes' exited non-zero, make sure environment variable KUBECONFIG is set to a working kubeconfig

### ISSUE THREAD

**Issue by gcraenen** [rancher/rancher-cleanup#68]
I'm getting this error when I run the script:

Running cleanup.sh version unreleased
==================== WARNING ====================
THIS WILL DELETE ALL RESOURCES CREATED BY RANCHER
MAKE SURE YOU HAVE CREATED AND TESTED YOUR BACKUPS
THIS IS A NON REVERSIBLE ACTION
==================== WARNING ====================
'kubectl get nodes' exited non-zero, make sure environment variable KUBECONFIG is set to a working kubeconfig

I have a working kubeconfig environment set:

kubectl get nodes gives:

NAME      STATUS   ROLES                              AGE    VERSION
node001   Ready    control-plane,etcd,master,worker   157d   v1.24.13+k3s1
node002   Ready    control-plane,etcd,master,worker   157d   v1.24.13+k3s1
node003   Ready    control-plane,etcd,master,worker   157d   v1.24.13+k3s1
node004   Ready    <none>                             75d    v1.27.3+k3s1
node005   Ready    <none>                             75d    v1.27.3+k3s1

**Comment by superseb** [comment]
How are you running it? Are you using the container image or the script directly? Please provide the exact commands you are using to determine why it is not working, it can't exit non-zero while it works fine manually as it runs the same commands. And as it says `version unreleased` it means you are not using the container image?

**Comment by gcraenen** [comment]
I'm running it as a kubernetes job with 'kubectl create -f deploy/rancher-cleanup.yaml' from a mac pro / macos.

When running on Ubuntu I run the clean.sh script and it runs ok.

**Comment by superseb** [comment]
The `latest` image should return `v1.0.2` as version, did you run it just now?

```
$ docker run --pull=always rancher/rancher-cleanup:latest
latest: Pulling from rancher/rancher-cleanup
Digest: sha256:e784267bcdd2e2b1e5a5e76b05c056058bee455de5579165ffd326ea0ed2d9de
Status: Image is up to date for rancher/rancher-cleanup:latest
Running cleanup.sh version v1.0.2
==================== WARNING ====================
THIS WILL DELETE ALL RESOURCES CREATED BY RANCHER
MAKE SURE YOU HAVE CREATED AND TESTED YOUR BACKUPS
THIS IS A NON REVERSIBLE ACTION
==================== WARNING ====================
'kubectl get nodes' exited non-zero, make sure environment variable KUBECONFIG is set to a working kubeconfig file
```

I was going to ask what Kubernetes distro and version you were running but I see the `k3s` output, did you know you are running with nodes on v1.24 and v1.27?

Could you change the Job's entrypoint and see why it can't connect to the cluster to root cause the issue?
