### ISSUE TITLE
My k8s cluster NS `istio-system` had been deleted by cleanup.sh run in container of rancher-cleanup/deploy/rancher-cleanup.yaml

### ISSUE THREAD

**Issue by Cyberphysics** [rancher/rancher-cleanup#76]
Before I apply rancher-cleanup.yaml, I see the note:
This script will delete all Kubernetes resources belonging to/created by Rancher (including installed tools like logging/monitoring/opa gatekeeper/etc). Note: this does not remove any Longhorn resources.
But, I dont see any watchout key words like `istio`. And my `istio-system` including related resources in it was created handly rather than by `Rancher`.
So I apply the rancher-cleanup.yaml, and the `istio-system` gone, the cluster is test stage.
If I have  some wrong usage of the rancher-cleanup.yaml, please tell me .
And are there any method that let I  restore the `istio-system` resource to latest avaliable state?

**Comment by superseb** [comment]
See https://github.com/rancher/rancher-cleanup/issues/6#issuecomment-1281896512 and https://github.com/rancher/rancher-cleanup/issues/39. The PR was never finished and we haven't taken the time to add it.

I've created https://github.com/rancher/rancher-cleanup/issues/77 to have an issue that can be worked on.

**Comment by superseb** [comment]
Let's continue in https://github.com/rancher/rancher-cleanup/issues/77
