### ISSUE TITLE
Add better namespace detection or add conditional logic for removing tools namespaces

### ISSUE THREAD

**Issue by superseb** [rancher/rancher-cleanup#77]
Examples:

- #6 
- #39 
- #76 

We should either add better detection to the script for the namespaces (to ensure they are created from Rancher) or make it conditional to specify what namespaces to skip.

**Comment by superseb** [comment]
@Cyberphysics Do you have a test environment where you can test https://github.com/rancher/rancher-cleanup/pull/78 ?

**Comment by Cyberphysics** [comment]
> @Cyberphysics Do you have a test environment where you can test #78 ?

yes, I can test it now.
