### ISSUE TITLE
[BUG] Noticing Some Elements Left During Verification

### ISSUE THREAD

**Issue by irishgordo** [rancher/rancher-cleanup#87]
Hey there, hope the week is going well :smile: 
Really like this utility as it's super helpful!

Noticing that:
1. helm uninstall rancher -n cattle-system
1. deploying the cleanup job
1. watching logs
1. deploying the verify job
1. checking verify logs but for deprecations yields some items:
```
root@k3s-server-argp-vm:/home/ubuntu/rancher-cleanup/rancher-cleanup-main# kubectl  -n kube-system logs -l job-name=verify-job  -f | grep -v "is deprecated"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
error: the server doesn't have a resource type "podsecuritypolicy"
etcdsnapshotfiles.k3s.cattle.io
```

As it seems that it didn't cleanup the `etcdsnapshotfiles.k3s.cattle.io`?
But maybe that is to be left, as this is a single node cluster running K3s?

Thanks for any info/insight :smile:

**Comment by migs35323** [comment]
same issue,
https://github.com/rancher/rancher-cleanup/blob/d024406418614ba02b5c23522791202928481224/cleanup.sh#L274-L279

the IF command is returning a code 1, which is triggering the remove psp commands
even tough my system is 1.25 and doesn't have the psp enabled.

**Comment by irishgordo** [comment]
@migs35323 - thanks for adding that content to the issue, I'm glad I'm not the only one :laughing: :smile:
