### ISSUE TITLE
Cant pull image

### ISSUE THREAD

**Issue by pwnzor11** [rancher/rancher-cleanup#91]
Stuck indefinitely in crashloopbackoff due to image not being available for my platform.  Isn't this designed to work with k3s?

**Comment by mingyard** [comment]
me too：
 # kubectl create -f deploy/rancher-cleanup.yaml
 
serviceaccount/cleanup-service-account created
clusterrolebinding.rbac.authorization.k8s.io/cleanup-admin created
job.batch/cleanup-job created

# kubectl  -n kube-system logs -l job-name=cleanup-job  -f
Error from server (BadRequest): container "cleanup" in pod "cleanup-job-2sq8d" is waiting to start: ContainerCreating

**Comment by aadiene** [comment]
Facing same issue. And I suspect the cause to be target architecture on my side. 
Built images not compatible with arm64/aarch64.

**Comment by aadiene** [comment]
Just to confirm that building the image for arm64 arch was the trick to remove rancher components from my aarch64 cluster.
I got some errors on verify step though `error: the server doesn't have a resource type "podsecuritypolicy"` but it seems to be related to this issue [43043](https://github.com/rancher/rancher/issues/43043).
